#!/usr/bin/env sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "⏩ Skipping pre-push hook on main branch"
  exit 0
fi


echo "🔄 Validating types and search errors..."
npm run typecheck

echo "🆕 Fetching latest develop branch to compare changes..."
git fetch origin develop:develop

echo "🧪 Running Jest on modified files since develop..."
npx jest --changedSince=develop --passWithNoTests

echo "🦋 Seaching for changeset file..."
npm run version-check