name: PR Test Modified Files

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-enviroment/action.yml
        with:
          custom_token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      - name: Run tests for changed files
        run: npx jest --changedSince=${{ github.base_ref }} --passWithNoTests
